easy_admin:
    design:
        menu:
            - { label: 'Homepage', route: 'admin' }
            - { entity: 'User', label: 'Users', route: 'admin_user'}
    entities:
        User:
            class: App\Entity\User
            list:
                fields: ['id', 'firstName', 'lastName', 'phone', 'email','createdAt']
                filters: ['country', 'role', 'createdAt']
                max_results: 30
   
